
[tool.isort]
profile = "black"
skip_gitignore = true
float_to_top = true

[tool.ruff.lint]
# See https://docs.astral.sh/ruff/rules/
# Selection mostly copied from satpy
select = ["A", "B", "C90", "E4", "E7", "E9", "F", "I", "TID", "N", "Q", "S", "T20", "NPY"]
ignore = ["S603"]

[tool.ruff.lint.mccabe]
max-complexity = 10
